# Generated by Django 3.2.2 on 2021-06-01 16:19

from django.conf import settings
from django.db import migrations
from django.db.backends.postgresql.schema import DatabaseSchemaEditor
from django.db.migrations.state import StateApps


def create_realm_user_default_table(apps: StateApps, schema_editor: DatabaseSchemaEditor) -> None:
    Realm = apps.get_model("zerver", "Realm")
    RealmUserDefault = apps.get_model("zerver", "RealmUserDefault")
    # We exclude the "SYSTEM_BOT_REALM" here because this realm only contains
    # Zulip "system bots" and will have no use of this table.
    realms = Realm.objects.exclude(string_id=settings.SYSTEM_BOT_REALM)
    for realm in realms:
        RealmUserDefault.objects.create(realm=realm)


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0340_rename_mutedtopic_to_usertopic"),
    ]

    operations = [
        migrations.RunPython(
            create_realm_user_default_table, reverse_code=migrations.RunPython.noop, elidable=True
        ),
    ]
