# Generated by Django 3.2.2 on 2021-06-07 09:08

from django.conf import settings
from django.db import migrations
from django.db.backends.postgresql.schema import DatabaseSchemaEditor
from django.db.migrations.state import StateApps


def migrate_existing_settings_to_realmuserdefault(
    apps: StateApps, schema_editor: DatabaseSchemaEditor
) -> None:
    Realm = apps.get_model("zerver", "Realm")
    RealmUserDefault = apps.get_model("zerver", "RealmUserDefault")
    realms = Realm.objects.exclude(string_id=settings.SYSTEM_BOT_REALM)
    for realm in realms:
        realm_user_default = RealmUserDefault.objects.get(realm=realm)
        realm_user_default.default_language = realm.default_language
        realm_user_default.twenty_four_hour_time = realm.default_twenty_four_hour_time
        realm_user_default.save(update_fields=["default_language", "twenty_four_hour_time"])


def reverse_migrating_existing_settings_to_realmuserdefault(
    apps: StateApps, schema_editor: DatabaseSchemaEditor
) -> None:
    Realm = apps.get_model("zerver", "Realm")
    RealmUserDefault = apps.get_model("zerver", "RealmUserDefault")
    realms = Realm.objects.exclude(string_id=settings.SYSTEM_BOT_REALM)
    for realm in realms:
        realm_user_default = RealmUserDefault.objects.get(realm=realm)
        realm.default_language = realm_user_default.default_language
        realm.default_twenty_four_hour_time = realm_user_default.twenty_four_hour_time
        realm.save(update_fields=["default_language", "default_twenty_four_hour_time"])


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0341_create_realm_user_default_table"),
    ]

    operations = [
        migrations.RunPython(
            migrate_existing_settings_to_realmuserdefault,
            reverse_code=reverse_migrating_existing_settings_to_realmuserdefault,
            elidable=True,
        ),
    ]
