# Generated by Django 3.2.4 on 2021-06-16 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0342_migrate_existing_settings_to_realmuserdefault"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="realm",
            name="default_language",
        ),
        migrations.RemoveField(
            model_name="realm",
            name="default_twenty_four_hour_time",
        ),
    ]
