# Generated by Django 4.2.4 on 2023-08-21 16:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0468_rename_followup_day_email_templates"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="userprofile",
            managers=[],
        ),
    ]
